
2023_hacktoberfest:
  - 2023_Hacktoberfest/**

eventvideos: 
  - 2023_Hacktoberfest/EventVideos/*

interactivefiction-API_antics:
  - 2023_Hacktoberfest/InteractiveFiction-API_Antics/*

hackgreenvilleeventsAPItestsuite:
  - HackGreenvilleEventsAPITestSuite/**

assets/readme: 
  - assets/readme/*

documentation: 
  - assets/readme/*
  - '**/*.txt'
  - '**/CONTRIBUTING.md'
  - '**/README.md'

repo:
  - '*'
