# Action Name
name: Run Newman as a GitHub Action

# How is this action triggered?
on:
  schedule: # Run on a schedule
  - cron: "0 10,16 * * *"
  workflow_dispatch: #Trigger manually

# This is the job that will run.
jobs:
  test-api:
    runs-on: ubuntu-latest

    # These are the steps within the job.
    steps: 
    # 1. Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v1

    # 2. Install Newman HTML Reporter
    - name: Install Newman HTML Reporter
      run: npm install -g newman-reporter-htmlextra

    # 3. Run Newman with params
    - name: Run Newman
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: HackGreenvilleEventsAPITestSuite/EventsAPI.json
        reporters: cli, html

    # 4. View Test Results in Console
    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary_full }} #summary_full is important!
    
    # 5. View results in HTML
    - name: View results in HTML
      run: newman run HackGreenvilleEventsAPITestSuite/EventsAPI.json -r htmlextra --reporter-htmlextra-export wwcgvl-newman.html
      
  # 6. Upload results to artifacts
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: wwcgvl-newman.html

    


